# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infographicsresume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='style',
            field=models.IntegerField(default=1),
        ),
    ]
