# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geomaps', '0002_shortlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlist',
            name='sitelabel',
            field=models.TextField(default='old site labels'),
            preserve_default=False,
        ),
    ]
