# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geomaps', '0003_shortlist_sitelabel'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlist',
            name='location',
            field=models.TextField(default='default_placeid'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shortlist',
            name='placeid',
            field=models.TextField(default='12.34,56.78'),
            preserve_default=False,
        ),
    ]
