# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 05:13
from __future__ import unicode_literals

from django.db import migrations, models
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('geopositioning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelSpot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', djgeojson.fields.PointField()),
            ],
        ),
        migrations.DeleteModel(
            name='PointOfInterest',
        ),
    ]
