# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geopositioning', '0002_auto_20170925_0513'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelspot',
            name='description',
            field=models.TextField(default='entry added'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='travelspot',
            name='picture',
            field=models.ImageField(default=[[255, 0, 0], [0, 255, 0], [0, 0, 255], [255, 255, 0]], upload_to=''),
            preserve_default=False,
        ),
    ]
