# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fortune',
            fields=[
                ('position', models.IntegerField(default=1)),
                ('name', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('value', models.IntegerField(default=1000)),
            ],
        ),
    ]
