# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geomaps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shortlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('val', models.TextField()),
                ('lat', models.TextField()),
                ('lng', models.TextField()),
                ('formatted_address', models.TextField()),
            ],
        ),
    ]
