# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geomaps', '0004_auto_20171008_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlist',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
