# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placesdata', '0003_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='id',
        ),
        migrations.AlterField(
            model_name='place',
            name='site_name',
            field=models.CharField(max_length=150, primary_key=True, serialize=False, verbose_name='site_name'),
        ),
    ]
