# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placesdata', '0006_auto_20170926_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='site_link',
            field=models.CharField(max_length=200, verbose_name='site_link'),
        ),
    ]
