# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-19 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelplan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveller',
            name='followers',
            field=models.ManyToManyField(blank=True, null=True, related_name='followees', to='travelplan.Traveller'),
        ),
    ]
