# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 09:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('site_state', models.CharField(max_length=100, verbose_name='site_state')),
                ('site_name', models.CharField(max_length=150, primary_key=True, serialize=False, verbose_name='site_name')),
                ('site_city_parent', models.CharField(max_length=50, verbose_name='site_city_parent')),
                ('site_link', models.CharField(max_length=200, verbose_name='site_link')),
                ('site_rating', models.FloatField(verbose_name='site_rating')),
                ('site_category', models.CharField(max_length=100, verbose_name='site_category')),
                ('site_speciality', models.CharField(max_length=100, verbose_name='site_speciality')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=100, verbose_name='State name')),
            ],
        ),
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=20)),
                ('details', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
