# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placesdata', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='name',
        ),
        migrations.AddField(
            model_name='place',
            name='site_category',
            field=models.CharField(default='default category', max_length=100, verbose_name='site_category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='site_city_parent',
            field=models.CharField(default='default city', max_length=50, verbose_name='site_city_parent'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='site_link',
            field=models.URLField(default='http://www.google.com/default_site.html', max_length=300, verbose_name='site_link'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='site_name',
            field=models.CharField(default='default site_name', max_length=150, verbose_name='site_name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='site_rating',
            field=models.FloatField(default=4.25, verbose_name='site_rating'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='site_speciality',
            field=models.CharField(default='default site spec', max_length=100, verbose_name='site_speciality'),
            preserve_default=False,
        ),
    ]
