# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placesdata', '0002_auto_20170925_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=100, verbose_name='State name')),
            ],
        ),
    ]
