# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placesdata', '0005_place_site_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='site_state',
            field=models.CharField(max_length=100, verbose_name='site_state'),
        ),
    ]
